### ISSUE TITLE
MyChatAlert toggle on/off notifications

### ISSUE THREAD

**Issue by SilverSaw** [brodyreeves/MyChatAlert#34]
Hello,

Currently there is no any kind of alert if you toggle mychatalert on or off with ctrl+right-click.

It would be great if we get something like different color on the minimap button or chat text which is notifying do i turn functionality on or off. It is confusing now and i have to click it 4-5 times and also i have to see if addon settings are available, just to be sure that addon functionality is on.

**Comment by brodyreeves** [comment]
Yeah I can make it change the icon color, it's something I've been meaning to do but haven't had the time. Until I get to this in the week or two, there actually is a change when you toggle on/off. The icon's tooltip will say whether a ctrl+right click will toggle alerts on (currently disabled) or whether it will toggle them off (currently enabled), unless you're not in the enUS locale and whichever locale you use has bad translations

**Comment by SilverSaw** [comment]
working like a charm, thanks !
