### ISSUE TITLE
[BUG] Addon re-enabling itself after zoning in and out of an instance.

### ISSUE THREAD

**Issue by padmanek** [brodyreeves/MyChatAlert#37]
**To Reproduce**

1. Ctrl+Left Click to Open Options
2. Uncheck "Enabled" checkbox.
3. Zone into instance. I've tried this with Zul Farrak.
4. Zone out.
5. Bug: addon enabled again or at least alerts are showing up again.

**Which version are you using?**

Latest 2.5.1.3

**Additonal Info**
"Disable in instance" is enabled.

**Comment by brodyreeves** [comment]
Had a feeling this would be an issue with the way I fixed instance disabling not working, just haven't had time to address it the past couple days but after my shift today I should be able to throw together a patch. Already have the solution in my head, simply need the time to sit down and put it together
