### ISSUE TITLE
Option to hide minimap icon[FEATURE]

### ISSUE THREAD

**Issue by Nordrassil** [brodyreeves/MyChatAlert#9]
title^^

**Comment by brodyreeves** [comment]
Will look into this, thought it would be as simple as adding another option, but based off the error I'm running into:  

```
1x MyChatAlert\minimap.lua:3: attempt to index field 'db' (a nil value)
```
I'm guessing that the minimap frame is being created before the db (saved variable storage) is created, I'll have to look into this to figure it out, when I find the time

edit: easier solution than expected, first time working with a minimap button so I forget they had their own saved variables set up
